name: Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  GOOGLE_CREDENTIALS: ${{ secrets.MINEIROS_TESTING_GCP_SA_KEY_FILE }}

concurrency:
  group: terraform-google-monitoring-notification-channel
  cancel-in-progress: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pre-commit
        run: make test/pre-commit
 
  # unit-tests:
  #   needs: pre-commit
  #   runs-on: ubuntu-latest
  #   name: Unit Tests
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Run Unit Tests
  #       run: make test/unit-tests
